name: Build Docker Image and Save as Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 构建 Docker 镜像
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: splayer:latest

    - name: 列出所有 Docker 镜像
      run: docker images


    - name: 保存 Docker 镜像到文件
      run: docker save -o splayer_image.tar splayer:latest

    - name: 上传镜像文件为 Artifact
      uses: actions/upload-artifact@v3
      with:
        name: splayer_image
        path: splayer_image.tar
